USE Restaurants;
GO

CREATE PROCEDURE sp_ResrvedTablesReport
    @StartDate DATE,
    @EndDate DATE
AS
BEGIN
    SELECT
        res.RESERVATION_ID,
        t.TABLE_ID,
        t.CAPACITY AS TABLE_CAPACITY,
        r.RESTAURANT_ID,
        r.NAME AS RESTAURANT_NAME,
        r.ADDRESS AS RESTAURANT_ADDRESS,
        res.RESERVATION_DATE,
        res.PARTY_SIZE
    FROM RESERVATION res
    INNER JOIN [TABLE] t ON res.TABLE_ID = t.TABLE_ID
    INNER JOIN RESTAURANT r ON t.RESTAURANT_ID = r.RESTAURANT_ID
    WHERE res.RESERVATION_DATE BETWEEN @StartDate AND @EndDate
    ORDER BY res.RESERVATION_DATE;
END;
GO
