USE Restaurants;
GO

CREATE VIEW vw_ReservationsReport AS
SELECT
    r.RESERVATION_ID,
    r.RESERVATION_DATE,
    r.PARTY_SIZE,
    
    t.TABLE_ID,
    t.CAPACITY AS TABLE_CAPACITY,
    
    rest.RESTAURANT_ID,
    rest.NAME AS RESTAURANT_NAME,
    rest.ADDRESS AS RESTAURANT_ADDRESS,
    rest.PHONE_NUMBER AS RESTAURANT_PHONE,
    
    c.CUSTOMER_ID,
    c.FIRST_NAME AS CUSTOMER_FIRST_NAME,
    c.LAST_NAME AS CUSTOMER_LAST_NAME,
    c.EMAIL AS CUSTOMER_EMAIL,
    c.PHONE AS CUSTOMER_PHONE
FROM RESERVATION r
INNER JOIN [TABLE] t ON r.TABLE_ID = t.TABLE_ID
INNER JOIN RESTAURANT rest ON r.RESTAURANT_ID = rest.RESTAURANT_ID
INNER JOIN CUSTOMER c ON r.CUSTOMER_ID = c.CUSTOMER_ID;
GO