USE Restaurants;
GO

CREATE VIEW vw_EmployeesWithRestaurant AS
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME AS EMPLOYEE_FIRST_NAME,
    e.LAST_NAME AS EMPLOYEE_LAST_NAME,
    e.POSITION,
    
    r.RESTAURANT_ID,
    r.NAME AS RESTAURANT_NAME,
    r.ADDRESS AS RESTAURANT_ADDRESS,
    r.PHONE_NUMBER AS RESTAURANT_PHONE,
    r.OPENING_HOURS
FROM EMPLOYEE e
INNER JOIN RESTAURANT r ON e.RESTAURANT_ID = r.RESTAURANT_ID;
GO