USE Restaurants;
GO

SELECT
    r.RESTAURANT_ID,
    r.NAME AS RESTAURANT_NAME,
    COUNT(res.RESERVATION_ID) AS ReservationCount,
    RANK() OVER (ORDER BY COUNT(res.RESERVATION_ID) DESC) AS PopularityRank
FROM RESTAURANT r
LEFT JOIN RESERVATION res ON r.RESTAURANT_ID = res.RESTAURANT_ID
GROUP BY r.RESTAURANT_ID, r.NAME
ORDER BY PopularityRank;
GO