USE Restaurants;
GO

--CREATE TABLE RESTAURANT (
--    RESTAURANT_ID VARCHAR(10) PRIMARY KEY,
--    NAME NVARCHAR(100),
--    OPENING_HOURS NVARCHAR(50),  
--    ADDRESS NVARCHAR(200),
--    PHONE_NUMBER VARCHAR(15)
--);


--CREATE TABLE MenuItems (
--    ITEM_ID VARCHAR(10) PRIMARY KEY,
--    RESTAURANT_ID VARCHAR(10),
--    NAME NVARCHAR(100),
--    DESCRIPTION NVARCHAR(50),  
--    PRICE DECIMAL(10,2),
--    CONSTRAINT FK_MenuItems_Restaurant
--        FOREIGN KEY (RESTAURANT_ID) REFERENCES Restaurants.dbo.RESTAURANT(RESTAURANT_ID)
--);


--CREATE TABLE EMPLOYEE(
--	EMPLOYEE_ID VARCHAR(10) PRIMARY KEY,
--	FIRST_NAME VARCHAR(20),
--	LAST_NAME VARCHAR(20),
--	RESTAURANT_ID VARCHAR(10),
--	POSITION VARCHAR(15),
--	CONSTRAINT FK_EMPLOYEE_Restaurant
--    FOREIGN KEY (RESTAURANT_ID) REFERENCES Restaurants.dbo.RESTAURANT(RESTAURANT_ID)
--);

--CREATE TABLE [TABLE](
--	TABLE_ID VARCHAR(10) PRIMARY KEY,
--	CAPACITY DECIMAL(10,0),
--	RESTAURANT_ID VARCHAR(10),
--	CONSTRAINT FK_TABLE_Restaurant
--    FOREIGN KEY (RESTAURANT_ID) REFERENCES Restaurants.dbo.RESTAURANT(RESTAURANT_ID)
--);

--CREATE TABLE CUSTOMER(
--	CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
--	FIRST_NAME VARCHAR(20),
--	LAST_NAME VARCHAR(20),
--	EMAIL VARCHAR(50),
--	PHONE VARCHAR(15),
--);

--CREATE TABLE RESERVATION(
--	RESERVATION_ID VARCHAR(10) PRIMARY KEY,
--	TABLE_ID VARCHAR(10),
--	RESTAURANT_ID VARCHAR(10),
--	CUSTOMER_ID VARCHAR(10),
--	PARTY_SIZE DECIMAL(10,2),
--	RESERVATION_DATE DATE,
--	CONSTRAINT FK_RESERVATION_TABLE
--    FOREIGN KEY (TABLE_ID) REFERENCES Restaurants.dbo.[TABLE] (TABLE_ID),
--	CONSTRAINT FK_RESERVATION_RESTAURANT
--    FOREIGN KEY (RESTAURANT_ID) REFERENCES Restaurants.dbo.RESTAURANT(RESTAURANT_ID),
--	CONSTRAINT FK_RESERVATION_CUSTOMER
--    FOREIGN KEY (CUSTOMER_ID) REFERENCES Restaurants.dbo.CUSTOMER(CUSTOMER_ID),
--);


--CREATE TABLE [ORDER](
--	ORDER_ID VARCHAR(10) PRIMARY KEY,
--	EMPLOYEE_ID VARCHAR(10),
--	RESERVATION_ID VARCHAR(10),
--	ORDER_DATE DATE,
--	TOTAL_AMOUNT DECIMAL(10,2),
--	CONSTRAINT FK_ORDER_EMPLOYEE
--	FOREIGN KEY (EMPLOYEE_ID) REFERENCES Restaurants.dbo.EMPLOYEE(EMPLOYEE_ID),
--	CONSTRAINT FK_ORDER_RESERVATION
--	FOREIGN KEY (RESERVATION_ID) REFERENCES Restaurants.dbo.RESERVATION(RESERVATION_ID),
--);

--CREATE TABLE ORDER_ITEM(
--	ORDER_ITEM_ID VARCHAR(10) PRIMARY KEY,
--	ITEM_ID VARCHAR(10),
--	ORDER_ID VARCHAR(10),
--	QUANTITY DECIMAL(10,0),
--	CONSTRAINT FK_ORDER_ITEM_MENUITEM
--       FOREIGN KEY (ITEM_ID) REFERENCES Restaurants.dbo.MenuItems(ITEM_ID),
--	CONSTRAINT FK_ORDER_ITEM_ORDER
--       FOREIGN KEY (ORDER_ID) REFERENCES Restaurants.dbo.[ORDER](ORDER_ID),

--);
